_target_: src.model.motions.DGSTGCN
num_frames: 100
gcn_ratio: 0.125
gcn_ctr: 'T'
gcn_ada: 'T'
tcn_ms_cfg: 
- [3, 1]
- [3, 2]
- [3, 3]
- [3, 4]
- ['max', 3]
- '1x1'
data_rep: ${data_rep}
dataset: humanml
graph_cfg:
  mode: 'random'
  num_filter: 8
  init_off: .04
  init_std: .02
latent_dim: ${common_space_dim}
vae: true