_target_: src.model.motions.MoViT
num_frames: 100
embed_dims: 256
num_heads: 1
num_transformer_layers: 3
dropout_p: 0.1
tube_size: 1
attention_type: 'divided_space_time' #'fact_encoder'
use_learnable_pos_emb: False
body_repres: 'body-parts'
use_time_padding_mask: True
use_skeleton_connection_mask: False
uniform_sample: True
data_rep: ${data_rep}
dataset: humanml
latent_dim: ${common_space_dim}
vae: true