from .contrastive_adaptive_CMGSD import ContrastiveAdaptiveCMGSD
from .contrastive_fixed import ContrastiveFixed
from .info_nce import InfoNCELoss
from .info_nce_cross_consistent import InfoNCECrossConsistent
from .tmr_losses import InfoNCE_with_filtering
from .soft_contrastive import SoftContrastiveLoss