trainer:
  _target_: pytorch_lightning.Trainer

  max_epochs: 250
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  accelerator: gpu
  devices: 1

  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: latest-{epoch}
      every_n_epochs: 1
      save_top_k: 1
      save_last: false
      enable_version_counter: false
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: best-rsum-{epoch}
      monitor: val_rsum_epoch
      mode: max
      every_n_epochs: 1
      save_top_k: 1
      save_last: false
      enable_version_counter: false
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: best-rsum-t2m-{epoch}
      monitor: val_rsum-t2m_epoch
      mode: max
      every_n_epochs: 1
      save_top_k: 1
      save_last: false
      enable_version_counter: false
    # - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    #   filename: best-motion-length-{epoch}
    #   monitor: val_motion_length_abs_error
    #   mode: min
    #   every_n_epochs: 1
    #   save_top_k: 1
    #   save_last: false
    #   enable_version_counter: false
    # - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    #   filename: best-val-loss-{epoch}
    #   monitor: val_loss
    #   mode: min
    #   every_n_epochs: 1
    #   save_top_k: 1
    #   save_last: false
    #   enable_version_counter: false
    # - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    #   filename: best-medr-{epoch}
    #   monitor: val_medr_epoch
    #   mode: min
    #   every_n_epochs: 1
    #   save_top_k: 1
    #   save_last: false
    #   enable_version_counter: false
    - _target_: src.callback.progress.ProgressLogger
      precision: 3
    - _target_: src.callback.tqdmbar.TQDMProgressBar

  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ${run_dir}
    name: logs
    version: ""

  # logger:
  #   _target_: src.logger.csv.CSVLogger
  #   save_dir: ${run_dir}
  #   name: logs
