_target_: src.model.losses.InfoNCECrossConsistent
max_violation_after: 15
single_modal_space_dim: 256
lambda_start_epoch: 0
lambda_end_epoch: 1
infonce_loss_fn: null
temperature: 0.1
cross_consistent_type: kldiv